license="MIT"
modLoader="javafml"
loaderVersion="[40,41)"
issueTrackerURL="https://github.com/supermassimo/DynamicTreesVarietyAddon/issues"

[[mods]]
modId="dtvariety"
version="${file.jarVersion}"
displayName="Dynamic Trees Variety Addon"
credits="Ferreusveritas, Max Hyper/supermassimo, Harley O'Connor"
authors="djs"
description='''
Vanilla addon for Dynamic Trees'''

[[dependencies.dtvariety]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.51,41)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtvariety]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtvariety]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[0.11.0,)"
    ordering="AFTER"
    side="BOTH"
